All routes
WildCodeSchool/p3-g2-sept21-lille-reactJs-eQay-frontend pull request #16
Opened 2022-01-10 11:28 UTC by Mariion-62

2022-01-10 14:22 UTC, PierreGoe submitted a review, later dismissed

2022-01-10 15:47 UTC, Hacene010 requested changes
saw one small evil

2022-01-10 15:47 UTC, Hacene010 commented on src/Components/BurgerMenu/index.jsx
> +        <Link id="home" className="menu-item" to="/">
ClassNames in camelCase plz

2022-01-11 10:36 UTC, PierreGoe approved these changes

2022-01-11 11:11 UTC, Hacene010 approved these changes

2022-01-11 13:18 UTC, merged