Filter mesure
WildCodeSchool/p3-g2-sept21-lille-reactJs-eQay-frontend pull request #17
Opened 2022-01-11 10:38 UTC by PierreGoe

2022-01-11 13:51 UTC, Mariion-62 approved these changes, later dismissed

2022-01-12 10:15 UTC, Hacene010 requested changes
Some empty lines to remove :-)

2022-01-12 10:15 UTC, Hacene010 commented on src/Components/Filter/style.jsx
> +
empty line !

2022-01-12 10:15 UTC, Hacene010 commented on src/Components/Filter/style.jsx
> +
empty line !

2022-01-12 10:15 UTC, Hacene010 commented on src/Components/Filter/style.jsx
> +
empty line !

2022-01-12 10:15 UTC, Hacene010 commented on src/Components/Filter/style.jsx
> +
empty line !

2022-01-12 10:15 UTC, Hacene010 commented on src/Components/Filter/style.jsx
> +
empty line !

2022-01-12 10:15 UTC, Hacene010 commented on src/Components/Filter/style.jsx
> +
empty line !

2022-01-12 10:15 UTC, Hacene010 commented on src/Components/MarkerIndoor/index.jsx
>  import L from 'leaflet';
Think about the next dev who will work on this project :-P (What is L for ?)

2022-01-12 13:22 UTC, Mariion-62 approved these changes

2022-01-12 14:02 UTC, Hacene010 approved these changes

2022-01-12 16:14 UTC, merged