Add function a zoom Location
WildCodeSchool/p3-g2-sept21-lille-reactJs-eQay-frontend pull request #25
Opened 2022-01-13 13:03 UTC by LuigiMenez

2022-01-13 13:04 UTC, PierreGoe approved these changes, later dismissed

2022-01-14 10:54 UTC, Hacene010 requested changes

2022-01-14 10:54 UTC, Hacene010 commented on src/Components/LocateUser/index.jsx
> +        // map.flyTo(e.latlng, map.getZoom());
dead code !

2022-01-14 12:59 UTC, PierreGoe approved these changes

2022-01-14 13:06 UTC, Hacene010 approved these changes

2022-01-14 13:11 UTC, merged